apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test-app-prod
  namespace: prod
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: test-app
        namespace: test
      valuesFiles:
        - ./helm/values.yaml
        - ./helm/values-prod.yaml
      interval: 1m
  values:
    replicaCount: 2