apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: test-app
  namespace: flux-system
spec:
  image: docker.io/vishaltte/test-app
  interval: 1m
  secretRef:
    name: dockercred
