---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-app
  namespace: test
spec:
  interval: 1m0s
  url: https://github.com/vishu42/flux-demo
  ref:
    branch: develop